trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'ba46c181-ee0e-464a-865f-8801bd1018f4'
- task: VSBuild@1
  displayName: 'Integration'
  inputs:
    solution: 'CodeAnalyzers.Episerver.Integration.sln'
    configuration: $(buildConfiguration)
    clean: true
